#!/usr/bin/env python3
"""Generate the bundled-profiles index at docs/profiles/index.md.

The repo ships one or more vehicle profiles under ``profiles/``. Rather than
hand-maintaining a list that drifts as profiles are added or grow, this scans
the bundled profiles, computes their headline counts (ECUs / PIDs / parameters /
verified), and renders a Markdown table — each row linking to the profile's
folder on GitHub.

It also refreshes the **"At a glance"** stats block on each profile's dedicated
tour page (see ``DEDICATED_PAGES``), which is delimited by the
``<!-- BEGIN/END generated-stats -->`` markers. Those pages are otherwise
hand-written prose; only the numbers inside the markers are managed here, so the
same counts can't drift out of sync with the index (they did: the page claimed
350 parameters / 223 verified / 96 open leads against an actual 354 / 227 / 58).

Usage:
    uv run scripts/gen_profiles_index.py            # write the page
    uv run scripts/gen_profiles_index.py --check     # fail if stale (CI)

Run it after adding a bundled profile or when a profile's headline counts change
enough to matter. CI checks the page is current (see .github/workflows/ci.yml).
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PROFILES_DIR = REPO_ROOT / "profiles"
OUT_PATH = REPO_ROOT / "docs" / "profiles" / "index.md"
GITHUB_TREE = "https://github.com/philipkocanda/canair/tree/main/profiles"

# Managed-block markers on a dedicated profile page. Everything between them is
# regenerated; the surrounding prose is hand-written and left untouched.
STATS_BEGIN = "<!-- BEGIN generated-stats -->"
STATS_END = "<!-- END generated-stats -->"
GENERATED_NOTE = (
    "<!-- GENERATED by scripts/gen_profiles_index.py — do not edit by hand. "
    "Regenerate after adding/changing a bundled profile. -->"
)

# Profiles that have their own dedicated tour page under docs/profiles/.
DEDICATED_PAGES = {"ioniq-2017": "ioniq-2017.md"}


def _profile_stats(ecus_dir: Path) -> dict[str, int]:
    """Headline counts for one profile, loaded straight from its ecus/ files."""
    from canlib.pids import load_pids, pid_status

    data = load_pids(ecus_dir) if ecus_dir.is_dir() else {"ecus": {}}
    ecus = data.get("ecus") or {}

    # Counts mirror `canair validate pids --stats` (the canonical headline): the
    # PID count is every defined PID (including `ignored` tombstones), while
    # parameters/verified are only counted on non-ignored PIDs.
    counts = {"ecus": 0, "pids": 0, "params": 0, "verified": 0, "iocontrol": 0, "research": 0}
    for ecu_def in ecus.values():
        if not isinstance(ecu_def, dict):
            continue
        counts["ecus"] += 1
        pids = ecu_def.get("pids") or {}
        for pid_def in pids.values():
            if not isinstance(pid_def, dict):
                continue
            counts["pids"] += 1
            if pid_status(pid_def) == "ignored":
                continue
            for param in (pid_def.get("parameters") or {}).values():
                if not isinstance(param, dict):
                    continue
                counts["params"] += 1
                if param.get("verified"):
                    counts["verified"] += 1
        counts["iocontrol"] += len(ecu_def.get("iocontrol") or {})
        # Open research leads, matching `canair research`'s default view: every
        # item whose status isn't `done` (see commands/research.py::_filter).
        for item in ecu_def.get("research") or []:
            if isinstance(item, dict) and item.get("status") != "done":
                counts["research"] += 1
    return counts


def _car_model(root: Path) -> str:
    import yaml

    meta_path = root / "profile.yaml"
    if meta_path.exists():
        meta = yaml.safe_load(meta_path.read_text()) or {}
        model = meta.get("car_model")
        if model:
            return str(model)
    return "—"


def _discover_bundled() -> list[tuple[str, Path]]:
    """(name, root) for each bundled profile, sorted by name."""
    if not PROFILES_DIR.is_dir():
        return []
    profiles = []
    for child in sorted(PROFILES_DIR.iterdir()):
        if child.is_dir() and ((child / "ecus").is_dir() or (child / "profile.yaml").exists()):
            profiles.append((child.name, child))
    return profiles


def _maturity(counts: dict[str, int]) -> str:
    """A one-word maturity hint from the counts."""
    if counts["verified"] >= 20:
        return "mature"
    if counts["params"] <= 2 and counts["ecus"] <= 2:
        return "seed / stub"
    return "early"


def render_stats_block(counts: dict[str, int]) -> str:
    """The managed "At a glance" rows for a dedicated profile page.

    Only the derived counts live here; the vehicle description row above them is
    hand-written prose outside the markers.
    """
    unverified = counts["params"] - counts["verified"]
    return "\n".join(
        [
            STATS_BEGIN,
            f"| ECUs mapped | **{counts['ecus']}** (all registered with identity) |",
            f"| PIDs | **{counts['pids']}** active/draft |",
            f"| Parameters | **{counts['params']}** decoded "
            f"(**{counts['verified']} verified**, {unverified} unverified/candidate) |",
            f"| IOControl DIDs | **{counts['iocontrol']}** actuators (UDS `0x2F`) |",
            f"| Research backlog | **{counts['research']}** open reverse-engineering leads |",
            STATS_END,
        ]
    )


def update_dedicated_page(path: Path, counts: dict[str, int]) -> str:
    """Return ``path``'s content with its managed stats block refreshed."""
    text = path.read_text()
    pattern = re.compile(
        re.escape(STATS_BEGIN) + r".*?" + re.escape(STATS_END),
        re.DOTALL,
    )
    if not pattern.search(text):
        raise SystemExit(
            f"{path.relative_to(REPO_ROOT)} has no "
            f"{STATS_BEGIN} / {STATS_END} block — add one around its "
            '"At a glance" count rows.'
        )
    return pattern.sub(lambda _m: render_stats_block(counts), text)


def dedicated_page_targets() -> list[tuple[Path, str]]:
    """``(path, wanted_content)`` for every dedicated profile page."""
    targets = []
    for name, root in _discover_bundled():
        page = DEDICATED_PAGES.get(name)
        if not page:
            continue
        path = OUT_PATH.parent / page
        if not path.exists():
            continue
        targets.append((path, update_dedicated_page(path, _profile_stats(root / "ecus"))))
    return targets


def generate() -> str:
    profiles = _discover_bundled()

    lines = [
        GENERATED_NOTE,
        "",
        "# Bundled profiles",
        "",
        "The repo ships these vehicle profiles under "
        f"[`profiles/`]({GITHUB_TREE}). Each is a self-contained "
        "[profile bundle](../concepts/profiles.md) you can select with "
        "`--profile NAME`. Build one for *your* car with the "
        "[bring-your-own-car](../bring-your-own-car/overview.md) journey — and "
        "please [contribute it back](../bring-your-own-car/08-share.md#contribute-your-profile-back).",
        "",
        "> These counts are generated from each profile's `ecus/` files by "
        "`scripts/gen_profiles_index.py`, so they stay in sync with the data.",
        "",
        "| Profile | Vehicle | ECUs | PIDs | Params | Verified | Maturity | Source |",
        "|---|---|---:|---:|---:|---:|---|---|",
    ]

    for name, root in profiles:
        counts = _profile_stats(root / "ecus")
        model = _car_model(root)
        page = DEDICATED_PAGES.get(name)
        name_cell = f"[{name}]({page})" if page else f"`{name}`"
        source = f"[`profiles/{name}/`]({GITHUB_TREE}/{name})"
        lines.append(
            f"| {name_cell} | {model} | {counts['ecus']} | {counts['pids']} | "
            f"{counts['params']} | {counts['verified']} | {_maturity(counts)} | {source} |"
        )

    lines += [
        "",
        "## The profiles",
        "",
    ]
    for name, root in profiles:
        counts = _profile_stats(root / "ecus")
        model = _car_model(root)
        page = DEDICATED_PAGES.get(name)
        source = f"[`profiles/{name}/`]({GITHUB_TREE}/{name})"
        if page:
            lines.append(
                f"- **[{name}]({page})** — {model}. "
                f"A mature, worked reference profile ({counts['verified']} verified "
                f"parameters across {counts['ecus']} ECUs). See the full tour, or "
                f"browse {source}."
            )
        else:
            n = counts["params"]
            params_str = f"{n} parameter" + ("" if n == 1 else "s")
            lines.append(
                f"- **`{name}`** — {model}. An early {_maturity(counts)} profile "
                f"({params_str}, {counts['verified']} verified) — a "
                f"starting point that needs contributions. Browse {source}."
            )
    lines.append("")

    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if a page differs from what would be generated (CI).",
    )
    args = ap.parse_args(argv)

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    # (path, wanted) for the index plus every dedicated page's stats block.
    targets: list[tuple[Path, str]] = [(OUT_PATH, generate()), *dedicated_page_targets()]

    if args.check:
        stale = [p for p, wanted in targets if (p.read_text() if p.exists() else None) != wanted]
        if stale:
            names = ", ".join(str(p.relative_to(REPO_ROOT)) for p in stale)
            print(
                f"Bundled-profile docs are out of date ({names}); run "
                "`uv run scripts/gen_profiles_index.py`.",
                file=sys.stderr,
            )
            return 1
        print("Bundled-profiles index is up to date.")
        return 0

    for path, wanted in targets:
        if (path.read_text() if path.exists() else None) == wanted:
            continue
        path.write_text(wanted)
        print(f"Wrote {path.relative_to(REPO_ROOT)}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
