#!/usr/bin/env python3
"""Generate the per-command CLI reference under docs/reference/cli/ from --help.

The CLI's argparse help is the single source of truth for flags and usage, so we
render it into Markdown rather than hand-maintaining a copy that drifts. Each
top-level `canair <cmd>` becomes docs/reference/cli/<cmd>.md, including one level
of nested sub-kinds (e.g. `scan range`, `ecu add`, `wican autopid write`).

Usage:
    python3 scripts/gen_cli_reference.py            # write the pages
    python3 scripts/gen_cli_reference.py --check     # fail if pages are stale (CI)

Run it after changing any command's parser (add/rename a flag, a new subcommand).
"""

from __future__ import annotations

import argparse
import io
import os
import sys
import tempfile
from contextlib import redirect_stdout
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = REPO_ROOT / "docs" / "reference" / "cli"
GENERATED_NOTE = (
    "<!-- GENERATED by scripts/gen_cli_reference.py — do not edit by hand. "
    "Regenerate after changing a command's parser. -->"
)


def _isolate_environment() -> None:
    """Make help output reproducible across machines/CI.

    Some `--help` strings embed config-resolved defaults (e.g. the `--wican`
    default reads `default_wican` from config). Both the user config
    (`$XDG_CONFIG_HOME/canair/config.yaml`) and a legacy gitignored repo-root
    `config.yaml` feed that resolution, so generation would otherwise depend on
    whoever's local config happens to be present (and CI, which has neither,
    would disagree). Force an empty config and clear the relevant env vars so the
    output is identical everywhere.
    """
    tmp = tempfile.mkdtemp(prefix="canair-genref-")
    os.environ["XDG_CONFIG_HOME"] = tmp
    for var in ("CANAIR_PROFILE", "CANAIR_PROFILES_DIR"):
        os.environ.pop(var, None)

    # Neutralize both config sources (user + legacy repo-local) deterministically.
    from canlib import config

    config.load_config.cache_clear()
    config.load_config = lambda: {}  # type: ignore[assignment]


def _format_help(parser: argparse.ArgumentParser) -> str:
    """Capture a parser's --help text (argparse writes to stdout via print_help)."""
    buf = io.StringIO()
    with redirect_stdout(buf):
        parser.print_help()
    return buf.getvalue().rstrip()


def _subparsers_action(parser: argparse.ArgumentParser):
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return action
    return None


def _render_command(name: str, parser: argparse.ArgumentParser) -> str:
    """Render one top-level command (and its nested sub-kinds) to Markdown."""
    lines = [GENERATED_NOTE, "", f"# `canair {name}`", ""]
    lines += ["```", _format_help(parser), "```", ""]

    sub = _subparsers_action(parser)
    if sub is not None:
        # choices maps sub-kind name -> its ArgumentParser (dedup shared parsers).
        seen: set[int] = set()
        for kind, subparser in sub.choices.items():
            if id(subparser) in seen:
                continue
            seen.add(id(subparser))
            lines += [f"## `canair {name} {kind}`", ""]
            lines += ["```", _format_help(subparser), "```", ""]
    return "\n".join(lines).rstrip() + "\n"


def _index_page(names: list[str]) -> str:
    """Rewrite the cli/ index to list the generated per-command pages."""
    from canlib.cli import build_parser

    parser = build_parser()
    sub = _subparsers_action(parser)
    help_by_name = {}
    if sub is not None:
        for n, p in sub.choices.items():
            help_by_name[n] = (p.description or "").strip().split("\n")[0]

    lines = [
        "# CLI reference",
        "",
        "Every capability is a `canair <subcommand>`. These pages are generated "
        "from each command's `--help` (the source of truth), so they never drift "
        "from the code.",
        "",
        "> Regenerate with `python3 scripts/gen_cli_reference.py`; CI checks they are current.",
        "",
        "## Commands",
        "",
    ]
    for n in names:
        summary = help_by_name.get(n, "")
        lines.append(f"- [`canair {n}`]({n}.md)" + (f" — {summary}" if summary else ""))
    lines.append("")
    return "\n".join(lines)


def generate() -> dict[str, str]:
    """Build the full set of {relative_path: content} for the cli/ reference."""
    from canlib.cli import build_parser
    from canlib.commands import COMMAND_NAMES

    parser = build_parser()
    sub = _subparsers_action(parser)
    assert sub is not None, "top-level parser has no subcommands"

    pages: dict[str, str] = {}
    for name in COMMAND_NAMES:
        subparser = sub.choices.get(name)
        if subparser is None:
            continue
        pages[f"{name}.md"] = _render_command(name, subparser)
    pages["index.md"] = _index_page(COMMAND_NAMES)
    return pages


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if any page differs from what would be generated (CI).",
    )
    args = ap.parse_args(argv)

    _isolate_environment()

    pages = generate()
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    stale: list[str] = []
    for rel, content in pages.items():
        path = OUT_DIR / rel
        current = path.read_text() if path.exists() else None
        if current != content:
            stale.append(rel)
            if not args.check:
                path.write_text(content)

    # Remove any stale generated pages no longer produced (except index).
    expected = set(pages) | {"index.md"}
    for path in OUT_DIR.glob("*.md"):
        if path.name not in expected:
            stale.append(path.name)
            if not args.check:
                path.unlink()

    if args.check:
        if stale:
            print(
                "CLI reference is out of date; run "
                "`python3 scripts/gen_cli_reference.py`. Stale: " + ", ".join(sorted(stale)),
                file=sys.stderr,
            )
            return 1
        print("CLI reference is up to date.")
        return 0

    print(f"Wrote {len(pages)} CLI reference page(s) to {OUT_DIR.relative_to(REPO_ROOT)}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
